// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250929065937_UpdatedUserTable")]
    partial class UpdatedUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("API.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            Id = "id-moh",
                            DisplayName = "Mohamad",
                            Email = "mohamad@example.com",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0]
                        },
                        new
                        {
                            Id = "id-hit",
                            DisplayName = "haitham",
                            Email = "haitham@example.com",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0]
                        },
                        new
                        {
                            Id = "id-hmsh",
                            DisplayName = "hashem",
                            Email = "hashem@example.com",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0]
                        },
                        new
                        {
                            Id = "id-os",
                            DisplayName = "osama",
                            Email = "osama@example.com",
                            PasswordHash = new byte[0],
                            PasswordSalt = new byte[0]
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
